SOURCES	+= qtuna.cpp \
	measure.cpp \
	jack.cpp \
	tools.cpp \
	halbbanddezimator.cpp \
	scala.cpp

# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qjacktuner

TARGET=../bin/qjacktuner
FORMS	= MainWindow.ui
TEMPLATE	=app
CONFIG	+= release thread qt
LIBS	+= -ljack
LANGUAGE	= C++
