You'll need qt and qt-devel >= 3.2, 
jack-audio-connection-kit and jack-audio-connection-kit-devel >= 0.98 installed.
Smaller Version numbers may work, but are untested.

To actually build open a shell,
cd into the directory, where this file resides,
type "qmake" <ENTER> and then "make" <ENTER>.
If everything is ok, there should be a file bin/qjacktuner now.

There is no make install yet.
You can "cp bin/qjacktuner /usr/local/bin" to have qjacktuner in a standard directory.

have fun,
Karsten
